# Generated by Django 4.2.1 on 2023-05-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_alter_redactor_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
