# Generated by Django 4.2.1 on 2023-05-28 13:39

from django.db import migrations


def load_fixture(apps, schema_editor):
    from django.core.management import call_command

    call_command("loaddata", "fixture_data.json")


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("agency", "0004_remove_newspaper_redactor_newspaper_redactors"),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
