# Generated by Django 4.2.1 on 2023-05-28 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0004_remove_newspaper_redactor_newspaper_redactors"),
        ("agency", "0005_auto_20230528_1639"),
    ]

    operations = []
